# Generated by Django 5.2.7 on 2025-10-17 12:53

from django.db import migrations

def add_default_gift_wraps(apps, schema_editor):
    GiftWrap = apps.get_model('orders', 'GiftWrap')
    
    # Create default gift wrap options
    gift_wraps = [
        {
            'name': 'Standard Gift Wrap',
            'description': 'Elegant wrapping paper with ribbon',
            'price': 2.99,
            'is_active': True
        },
        {
            'name': 'Premium Gift Wrap',
            'description': 'Luxury wrapping with decorative elements',
            'price': 4.99,
            'is_active': True
        },
        {
            'name': 'Festival Special Wrap',
            'description': 'Seasonal themed wrapping paper',
            'price': 3.99,
            'is_active': True
        }
    ]
    
    for gift_wrap_data in gift_wraps:
        GiftWrap.objects.get_or_create(
            name=gift_wrap_data['name'],
            defaults=gift_wrap_data
        )

def remove_default_gift_wraps(apps, schema_editor):
    GiftWrap = apps.get_model('orders', 'GiftWrap')
    GiftWrap.objects.filter(name__in=['Standard Gift Wrap', 'Premium Gift Wrap', 'Festival Special Wrap']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_giftwrap_cartitem_orders_cart_user_id_beaab2_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_gift_wraps, remove_default_gift_wraps),
    ]