# Generated by Django 5.2.7 on 2025-10-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_default_gift_wraps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_wrap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.giftwrap'),
        ),
    ]
