# Generated by Django 5.2.7 on 2025-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_giftboxcustomization_giftboxitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
