# Generated by Django 5.2.7 on 2025-10-17 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active'], name='cms_banner_is_acti_3d6642_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['order'], name='cms_banner_order_50eb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['created_at'], name='cms_banner_created_d35438_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email'], name='cms_newslet_email_6ec2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['is_active'], name='cms_newslet_is_acti_8a40a0_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['subscribed_at'], name='cms_newslet_subscri_2fc93e_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['confirmation_token'], name='cms_newslet_confirm_6e0454_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['page_type'], name='cms_page_page_ty_750b22_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_active'], name='cms_page_is_acti_831fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active'], name='cms_testimo_is_acti_4e9832_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['order'], name='cms_testimo_order_ce4b59_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['rating'], name='cms_testimo_rating_61e5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['created_at'], name='cms_testimo_created_a7aa68_idx'),
        ),
    ]
