# Generated by Django 5.2.7 on 2025-10-17 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_newsletter_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
