# Generated by Django 5.2.7 on 2025-10-17 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_newsletter_confirmation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('order', 'Order Support'), ('product', 'Product Information'), ('wholesale', 'Wholesale Inquiry'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='cms_enquiry_email_497226_idx'), models.Index(fields=['subject'], name='cms_enquiry_subject_224e01_idx'), models.Index(fields=['is_resolved'], name='cms_enquiry_is_reso_a97c2f_idx'), models.Index(fields=['created_at'], name='cms_enquiry_created_706a77_idx')],
            },
        ),
    ]
