# Generated by Django 5.2.7 on 2025-10-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('shipping', 'Shipping Policy'), ('returns', 'Returns & Refunds'), ('careers', 'Careers')], max_length=20, unique=True),
        ),
    ]
