# Generated by Django 5.2.7 on 2025-10-18 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g., 'heart-pulse', 'calendar')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='cms_careers_is_acti_e0375d_idx'), models.Index(fields=['order'], name='cms_careers_order_178741_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareersCultureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g., 'heart', 'users')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='cms_careers_is_acti_ef2c98_idx'), models.Index(fields=['order'], name='cms_careers_order_f11fdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareersJobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='cms_careers_is_acti_ed4ef3_idx'), models.Index(fields=['order'], name='cms_careers_order_a4b730_idx'), models.Index(fields=['department'], name='cms_careers_departm_266721_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('culture', 'Culture Section'), ('testimonials', 'Testimonials Section'), ('benefits', 'Benefits Section'), ('openings', 'Job Openings Section'), ('cta', 'Call to Action Section')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'section_type'],
                'indexes': [models.Index(fields=['section_type'], name='cms_careers_section_77fe97_idx'), models.Index(fields=['is_active'], name='cms_careers_is_acti_c1b1c6_idx'), models.Index(fields=['order'], name='cms_careers_order_bc383c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareersTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='cms_careers_is_acti_3c50b9_idx'), models.Index(fields=['order'], name='cms_careers_order_15e473_idx')],
            },
        ),
    ]
