# Generated by Django 5.2.7 on 2025-10-18 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_careersbenefit_careerscultureitem_careersjobopening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='DRY FRUITS DELIGHT', max_length=100)),
                ('copyright_text', models.CharField(default='© 2024 DRY FRUITS DELIGHT. All rights reserved.', max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g., 'leaf', 'award')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Homepage Feature',
                'verbose_name_plural': 'Homepage Features',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='cms_homepag_is_acti_16f7a2_idx'), models.Index(fields=['order'], name='cms_homepag_order_d26218_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomePageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Homepage Hero',
                'verbose_name_plural': 'Homepage Heroes',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='cms_homepag_is_acti_2e9d25_idx'), models.Index(fields=['order'], name='cms_homepag_order_254a40_idx')],
            },
        ),
    ]
