# Generated by Django 5.2.7 on 2025-10-17 12:37

from django.db import migrations
from django.utils import timezone

def add_low_stock_template(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    
    # Create low stock alert template
    EmailTemplate.objects.get_or_create(
        template_type='low_stock_alert',
        defaults={
            'subject': 'Low Stock Alert for {{product_name}}',
            'body_html': '''
            <p>Hello Admin,</p>
            <p>This is a low stock alert for the following product:</p>
            <ul>
                <li><strong>Product:</strong> {{product_name}}</li>
                <li><strong>Current Stock:</strong> {{current_stock}} units</li>
                <li><strong>Threshold:</strong> {{threshold}} units</li>
            </ul>
            <p>Please consider restocking this product soon.</p>
            <p><a href="{{product_url}}">View Product Details</a></p>
            <p>Thank you,<br>Your E-commerce Team</p>
            ''',
            'body_text': '''
            Hello Admin,
            
            This is a low stock alert for the following product:
            
            Product: {{product_name}}
            Current Stock: {{current_stock}} units
            Threshold: {{threshold}} units
            
            Please consider restocking this product soon.
            
            View Product Details: {{product_url}}
            
            Thank you,
            Your E-commerce Team
            ''',
            'is_active': True
        }
    )

def remove_low_stock_template(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    EmailTemplate.objects.filter(template_type='low_stock_alert').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_low_stock_template, remove_low_stock_template),
    ]