# Generated by Django 5.2.7 on 2025-10-17 13:10

from django.db import migrations

def add_new_enquiry_template(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    
    # Create new enquiry notification template
    EmailTemplate.objects.get_or_create(
        template_type='new_enquiry',
        defaults={
            'subject': 'New Customer Enquiry: {{subject}}',
            'body_html': '''
            <p>Hello Admin,</p>
            <p>A new customer enquiry has been submitted:</p>
            <ul>
                <li><strong>Name:</strong> {{name}}</li>
                <li><strong>Email:</strong> {{email}}</li>
                <li><strong>Phone:</strong> {{phone}}</li>
                <li><strong>Subject:</strong> {{subject}}</li>
            </ul>
            <p><strong>Message:</strong></p>
            <p>{{message}}</p>
            <p><a href="http://localhost:8000/admin-panel/enquiries/">View All Enquiries</a></p>
            <p>Thank you,<br>Your E-commerce Team</p>
            ''',
            'body_text': '''
            Hello Admin,
            
            A new customer enquiry has been submitted:
            
            Name: {{name}}
            Email: {{email}}
            Phone: {{phone}}
            Subject: {{subject}}
            
            Message:
            {{message}}
            
            View All Enquiries: http://localhost:8000/admin-panel/enquiries/
            
            Thank you,
            Your E-commerce Team
            ''',
            'is_active': True
        }
    )

def remove_new_enquiry_template(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    EmailTemplate.objects.filter(template_type='new_enquiry').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_low_stock_template'),
    ]

    operations = [
        migrations.RunPython(add_new_enquiry_template, remove_new_enquiry_template),
    ]