# Generated by Django 5.2.7 on 2025-10-17 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_new_enquiry_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('low_stock_alert', 'Low Stock Alert')], max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-created_at'], name='notificatio_created_4c6dec_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='notificatio_status_18a272_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_02c093_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['template_type'], name='notificatio_templat_d25b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['template_type'], name='notificatio_templat_c5c732_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_0aa238_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['-created_at'], name='notificatio_created_b2ca4c_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status'], name='notificatio_status_532cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_1b06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['template_type'], name='notificatio_templat_03101d_idx'),
        ),
        migrations.AddIndex(
            model_name='smstemplate',
            index=models.Index(fields=['template_type'], name='notificatio_templat_0f140a_idx'),
        ),
        migrations.AddIndex(
            model_name='smstemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_e9b696_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_6936c2_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_6a3aac_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_07d5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['valid_until'], name='notificatio_valid_u_6412b5_idx'),
        ),
    ]
