# Generated by Django 5.2.7 on 2025-10-17 14:00

from django.db import migrations

def add_order_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    
    # Create order confirmation template
    EmailTemplate.objects.get_or_create(
        template_type='order_confirmation',
        defaults={
            'subject': 'Order Confirmation #{{order_number}}',
            'body_html': '''
            <p>Hello {{customer_name}},</p>
            <p>Thank you for your order! This email confirms that we have received your order.</p>
            
            <h3>Order Details:</h3>
            <ul>
                <li><strong>Order Number:</strong> {{order_number}}</li>
                <li><strong>Order Date:</strong> {{order_date}}</li>
                <li><strong>Total Amount:</strong> ₹{{order_total}}</li>
            </ul>
            
            <h3>Items Ordered:</h3>
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order_items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>₹{{ item.price }}</td>
                        <td>₹{{ item.total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <h3>Shipping Address:</h3>
            <p>{{ shipping_address }}</p>
            
            <p>We will send you another email when your order has been shipped.</p>
            <p><a href="{{order_url}}">View Order Details</a></p>
            
            <p>Thank you for shopping with us!<br>Your E-commerce Team</p>
            ''',
            'body_text': '''
            Hello {{customer_name}},
            
            Thank you for your order! This email confirms that we have received your order.
            
            Order Details:
            Order Number: {{order_number}}
            Order Date: {{order_date}}
            Total Amount: ₹{{order_total}}
            
            Items Ordered:
            {% for item in order_items %}
            - {{ item.name }} (Qty: {{ item.quantity }}) - ₹{{ item.total }}
            {% endfor %}
            
            Shipping Address:
            {{ shipping_address }}
            
            We will send you another email when your order has been shipped.
            
            View Order Details: {{order_url}}
            
            Thank you for shopping with us!
            Your E-commerce Team
            ''',
            'is_active': True
        }
    )
    
    # Create order shipped template
    EmailTemplate.objects.get_or_create(
        template_type='order_shipped',
        defaults={
            'subject': 'Your Order #{{order_number}} Has Been Shipped',
            'body_html': '''
            <p>Hello {{customer_name}},</p>
            <p>Great news! Your order has been shipped and is on its way to you.</p>
            
            <h3>Order Details:</h3>
            <ul>
                <li><strong>Order Number:</strong> {{order_number}}</li>
                <li><strong>Order Date:</strong> {{order_date}}</li>
                <li><strong>Total Amount:</strong> ₹{{order_total}}</li>
            </ul>
            
            <p>You can track your shipment using the tracking number provided by our shipping partner.</p>
            <p><a href="{{order_url}}">View Order Details</a></p>
            
            <p>Thank you for shopping with us!<br>Your E-commerce Team</p>
            ''',
            'body_text': '''
            Hello {{customer_name}},
            
            Great news! Your order has been shipped and is on its way to you.
            
            Order Details:
            Order Number: {{order_number}}
            Order Date: {{order_date}}
            Total Amount: ₹{{order_total}}
            
            You can track your shipment using the tracking number provided by our shipping partner.
            
            View Order Details: {{order_url}}
            
            Thank you for shopping with us!
            Your E-commerce Team
            ''',
            'is_active': True
        }
    )
    
    # Create order delivered template
    EmailTemplate.objects.get_or_create(
        template_type='order_delivered',
        defaults={
            'subject': 'Your Order #{{order_number}} Has Been Delivered',
            'body_html': '''
            <p>Hello {{customer_name}},</p>
            <p>We're happy to let you know that your order has been successfully delivered.</p>
            
            <h3>Order Details:</h3>
            <ul>
                <li><strong>Order Number:</strong> {{order_number}}</li>
                <li><strong>Order Date:</strong> {{order_date}}</li>
                <li><strong>Total Amount:</strong> ₹{{order_total}}</li>
            </ul>
            
            <p>We hope you're satisfied with your purchase. If you have any questions or concerns, please don't hesitate to contact us.</p>
            
            <h3>We'd Love Your Feedback!</h3>
            <p>Please take a moment to review your purchased items. Your feedback helps us improve our products and service.</p>
            <p><a href="{{order_url}}">Leave a Review</a></p>
            
            <p>Thank you for shopping with us!<br>Your E-commerce Team</p>
            ''',
            'body_text': '''
            Hello {{customer_name}},
            
            We're happy to let you know that your order has been successfully delivered.
            
            Order Details:
            Order Number: {{order_number}}
            Order Date: {{order_date}}
            Total Amount: ₹{{order_total}}
            
            We hope you're satisfied with your purchase. If you have any questions or concerns, please don't hesitate to contact us.
            
            We'd Love Your Feedback!
            Please take a moment to review your purchased items. Your feedback helps us improve our products and service.
            
            Leave a Review: {{order_url}}
            
            Thank you for shopping with us!
            Your E-commerce Team
            ''',
            'is_active': True
        }
    )

def remove_order_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
    EmailTemplate.objects.filter(template_type__in=['order_confirmation', 'order_shipped', 'order_delivered']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_emailtemplate_template_type_and_more'),
    ]

    operations = [
        migrations.RunPython(add_order_templates, remove_order_templates),
    ]